pacman -S bat --noconfirm
pacman -S cmatrix --noconfirm
pacman -S discord --noconfirm
pacman -S gparted --noconfirm
pacman -S grub-customizer --noconfirm
pacman -S hollywood --noconfirm
pacman -S htop --noconfirm
pacman -S kdeconnect --noconfirm
pacman -S lightdm --noconfirm
pacman -S lightdm-gtk-greeter --noconfirm
pacman -S lightdm-gtk-greeter-settings --noconfirm
pacman -S lightdm-slick-greeter --noconfirm
pacman -S lightdm-webkit-theme-aether --noconfirm
pacman -S lightdm-webkit2-greeter --noconfirm
pacman -S lightdm-webkit2-theme-glorious --noconfirm
pacman -S lsd --noconfirm
pacman -S lxappearance --noconfirm
pacman -S neofetch --noconfirm
pacman -S network-manager-applet --noconfirm
pacman -S networkmanager --noconfirm
pacman -S nitrogen --noconfirm
pacman -S nodejs --noconfirm
pacman -S notepadqq --noconfirm
pacman -S notification-daemon --noconfirm
pacman -S noto-fonts --noconfirm
pacman -S npm --noconfirm
pacman -S papirus-icon-theme --noconfirm
pacman -S pavucontrol --noconfirm
pacman -S picom --noconfirm
pacman -S ranger --noconfirm
pacman -S ruby --noconfirm
pacman -S spotifyd --noconfirm
pacman -S sqlite --noconfirm
pacman -S starship --noconfirm
pacman -S telegram-desktop --noconfirm
pacman -S vlc --noconfirm
pacman -S xclip --noconfirm
pacman -S zoom --noconfirm
pacman -S zsh --noconfirm

snap install brave
